### ISSUE TITLE
android 学习路线，第一个，今看打不开页面。望处理一下

### ISSUE THREAD

**Issue by 54zhangxin** [JohnTsaiAndroid/AndroidTips#3]

**Comment by johncaijing** [comment]
fixed by [https://github.com/JohnTsaiAndroid/AndroidTips/commit/049c9d9eb165bd1bf12a8e079752a384bb0fa47f](https://github.com/JohnTsaiAndroid/AndroidTips/commit/049c9d9eb165bd1bf12a8e079752a384bb0fa47f)
